server:
  port: 8080



spring:
  datasource:
    db1:
      jdbc-url: jdbc:mysql://localhost:3306/springboot
      username: root
      password: chenjie+00
    db2:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: chenjie+00



    # \u9ED8\u8BA4\u8BC6\u522B
#    driver-class-name: com.mysql.cj.jdbc.Driver


#mybatis.config-location=classpath:mybatis-config.xml
#logging.level.root=WARN
#logging.level.sample.mybatis.xml.mapper=TRACE

# \u65B9\u6848\u4E00\uFF1A \u901A\u8FC7\u914D\u7F6E\u6587\u4EF6\u627E\u5230mybatis-comfig.xml\u914D\u7F6E\u6587\u4EF6 --> \u7136\u540E\u627E\u5230mapper\uFF08mybatis/mapper/GuestMapper.xml\uFF09 --> \u8BE5\u6587\u4EF6\u548Cdao/GuestDao\u5173\u8054
mybatis:
  #config-location: classpath:mybatis-config.xml

#  mybatis.mapper-locations=classpath*:/mappers/*.xml
#  mybatis.type-aliases-package=sample.mybatis.thymeleaf.domain

# \u65B9\u6848\u4E8C\uFF1A\u66FF\u6362\u6389mybatis-config.xml\u6587\u4EF6
  #mapper-locations: classpath*:/mybatis/mapper/*.xml
  #type-aliases-package: com.cj.domain.Guest

# \u65B9\u6848\u4E09\uFF1A\u66FF\u6362\u6389\u6240\u6709\u7684xml\u6587\u4EF6(\u80FD\u901A\u8FC7@Mapper\u6CE8\u89E3\uFF0C\u4E0D\u7528\u5199mapper-locations)




