#server:
#  port: 8080
jasypt:
  encryptor:
    password: 123456!@#
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

userinfo:
  username: ENC(dQjA0bmo8685YI5OZVGzsQ==)
  password: ENC(5iHrt5u2ZOkO1G2LFSfB0w==)
#  username: 123456
#  password: 123456


food:
  meat: 烤肉
  rice: 米饭
  drink:
    - 矿泉水
    - 咖啡
    - 奶茶

# 指定当前环境
spring:
  profiles:
    active: "production"

---
# 开发环境
spring:
  config:
    activate:
      on-profile: "development"

server:
  port: 8081

---
# 生产环境
spring:
  config:
    activate:
      on-profile: "production"

server:
  port: 8082